variable "resource_group_name" {
  description = "Resource group name for compute resources"
  type        = string
}

variable "location" {
  description = "Azure location"
  type        = string
}

variable "private_subnet_id" {
  description = "ID of the private subnet where VMs will be placed"
  type        = string
}

variable "vm_count" {
  description = "Number of VMs to create"
  type        = number
  default     = 2
}

variable "vm_size" {
  description = "Azure VM size"
  type        = string
  default     = "Standard_B2s"
}

variable "admin_username" {
  description = "Admin username for the Linux VMs"
  type        = string
  default     = "azureuser"
}

variable "ssh_public_key" {
  description = "Optional SSH public key (openssh). If empty, one will be generated by the module and output as 'generated_private_key_pem'."
  type        = string
  default     = ""
}

variable "vm_name_prefix" {
  description = "Prefix for VM and NIC names"
  type        = string
  default     = "appvm"
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "user_assigned_identity_id" {
  description = "Optional user assigned identity id to attach to the VMs (for ACR pull)"
  type        = string
  default     = ""
}

variable "acr_name" {
  description = "ACR name (without .azurecr.io)"
  type        = string
  default     = ""
}

variable "acr_repository" {
  description = "Repository name in ACR"
  type        = string
  default     = "myapp"
}

variable "acr_tag" {
  description = "Image tag in ACR"
  type        = string
  default     = "latest"
}

